spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql = true
spring.datasource.url=jdbc:postgres://babgfjvnryiinv:7e9500659aa9f0bb5722867aeb2160010e0e58389740e1d765d162343662e473@ec2-54-228-125-183.eu-west-1.compute.amazonaws.com:5432/d2ooc9u750rico
spring.datasource.username=babgfjvnryiinv
spring.datasource.password=7e9500659aa9f0bb5722867aeb2160010e0e58389740e1d765d162343662e473
spring.datasource.driver-class-name=org.postgresql.Driver
